version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    groups:
      maven-dependencies:
        patterns:
          - "*"
  - package-ecosystem: maven
    target-branch: 2.5.x
    directory: "/"
    schedule:
      interval: weekly
    groups:
      maven-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: maven
    target-branch: 2.4.x
    directory: "/"
    schedule:
      interval: weekly
    groups:
      maven-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"