package dev.morphia.critter.parser.generator;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;

import dev.morphia.critter.CritterClassLoader;
import dev.morphia.critter.parser.FieldInfo;
import dev.morphia.critter.parser.MethodInfo;
import dev.morphia.critter.parser.PropertyFinder;
import dev.morphia.mapping.Mapper;

import io.github.dmlloyd.classfile.ClassFile;
import io.github.dmlloyd.classfile.ClassModel;

/**
 * Facade that orchestrates the full ClassFile-based code generation pipeline for a Morphia entity,
 * including field/method accessor injection and property/entity model generation.
 */
public class CritterGenerator {
    private final Mapper mapper;

    /**
     * Creates a new CritterGenerator with the given mapper.
     *
     * @param mapper the Morphia mapper
     */
    public CritterGenerator(Mapper mapper) {
        this.mapper = mapper;
    }

    /**
     * Reads the entity class bytecode, discovers its properties, and generates all required Critter support classes.
     *
     * @param type               the entity class to process
     * @param critterClassLoader the class loader that will receive generated bytecode
     * @param runtimeMode        {@code true} to generate VarHandle-based accessors for runtime use
     * @return the generated entity model generator
     */
    public EntityModelGenerator generate(Class<?> type, CritterClassLoader critterClassLoader, boolean runtimeMode) {
        String resourceName = "%s.class".formatted(type.getName().replace('.', '/'));
        InputStream inputStream = type.getClassLoader().getResourceAsStream(resourceName);
        if (inputStream == null) {
            throw new IllegalArgumentException("Could not find class file for %s".formatted(type.getName()));
        }
        ClassModel classModel;
        try {
            classModel = ClassFile.of().parse(inputStream.readAllBytes());
        } catch (IOException e) {
            throw new RuntimeException("Failed to read class %s".formatted(type.getName()), e);
        }
        PropertyFinder propertyFinder = new PropertyFinder(mapper, critterClassLoader, runtimeMode);

        return entityModel(type, critterClassLoader, classModel, propertyFinder.find(type, classModel));
    }

    /**
     * Reads the entity class bytecode, discovers its properties, and generates all required Critter support classes
     * using build-time (non-runtime) mode.
     *
     * @param type               the entity class to process
     * @param critterClassLoader the class loader that will receive generated bytecode
     * @return the generated entity model generator
     */
    public EntityModelGenerator generate(Class<?> type, CritterClassLoader critterClassLoader) {
        return generate(type, critterClassLoader, false);
    }

    /**
     * Generates bytecode augmenting the entity with synthetic {@code __readXxx}/{@code __writeXxx} methods for its fields.
     *
     * @param entityType the entity class to augment
     * @param fields     the fields for which accessor methods should be generated
     * @return the augmented class bytecode
     */
    public byte[] fieldAccessors(Class<?> entityType, List<FieldInfo> fields) {
        return new AddFieldAccessorMethods(entityType, fields).emit();
    }

    /**
     * Generates bytecode augmenting the entity with synthetic {@code __readXxx}/{@code __writeXxx} methods for its getter methods.
     *
     * @param entityType the entity class to augment
     * @param methods    the getter methods for which accessor methods should be generated
     * @return the augmented class bytecode
     */
    public byte[] methodAccessors(Class<?> entityType, List<MethodInfo> methods) {
        return new AddMethodAccessorMethods(entityType, methods).emit();
    }

    /**
     * Generates and registers a {@link PropertyAccessorGenerator} for the given field.
     *
     * @param entityType         the entity class that owns the field
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param field              the field for which a property accessor should be generated
     * @return the emitted property accessor generator
     */
    public PropertyAccessorGenerator propertyAccessor(Class<?> entityType, CritterClassLoader critterClassLoader, FieldInfo field) {
        return new PropertyAccessorGenerator(entityType, critterClassLoader, field).emit();
    }

    /**
     * Generates and registers a {@link PropertyAccessorGenerator} for the given getter method.
     *
     * @param entityType         the entity class that owns the method
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param method             the getter method for which a property accessor should be generated
     * @return the emitted property accessor generator
     */
    public PropertyAccessorGenerator propertyAccessor(Class<?> entityType, CritterClassLoader critterClassLoader, MethodInfo method) {
        return new PropertyAccessorGenerator(entityType, critterClassLoader, method).emit();
    }

    /**
     * Generates and registers a VarHandle-based accessor for the given field (used in runtime mode).
     *
     * @param entityType         the entity class that owns the field
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param field              the field for which a VarHandle accessor should be generated
     * @return the emitted VarHandle accessor generator
     */
    public VarHandleAccessorGenerator varHandleAccessor(Class<?> entityType, CritterClassLoader critterClassLoader, FieldInfo field) {
        return new VarHandleAccessorGenerator(entityType, critterClassLoader, field).emit();
    }

    /**
     * Generates and registers a VarHandle-based accessor for the property exposed by the given getter method (used in runtime mode).
     *
     * @param entityType         the entity class that owns the method
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param method             the getter method for which a VarHandle accessor should be generated
     * @return the emitted VarHandle accessor generator
     */
    public VarHandleAccessorGenerator varHandleAccessor(Class<?> entityType, CritterClassLoader critterClassLoader, MethodInfo method) {
        return new VarHandleAccessorGenerator(entityType, critterClassLoader, method).emit();
    }

    /**
     * Generates and registers a {@link PropertyModelGenerator} for the given field.
     *
     * @param entityType         the entity class that owns the field
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param field              the field for which a property model should be generated
     * @return the emitted property model generator
     */
    public PropertyModelGenerator propertyModelGenerator(Class<?> entityType, CritterClassLoader critterClassLoader, FieldInfo field) {
        return new PropertyModelGenerator(mapper.getConfig(), entityType, critterClassLoader, field).emit();
    }

    /**
     * Generates and registers a {@link PropertyModelGenerator} for the property exposed by the given getter method.
     *
     * @param entityType         the entity class that owns the method
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param method             the getter method for which a property model should be generated
     * @return the emitted property model generator
     */
    public PropertyModelGenerator propertyModelGenerator(Class<?> entityType, CritterClassLoader critterClassLoader, MethodInfo method) {
        return new PropertyModelGenerator(mapper.getConfig(), entityType, critterClassLoader, method).emit();
    }

    /**
     * Generates and registers the entity model class for the given type.
     *
     * @param type               the entity class
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param classModel         the ClassModel for the entity
     * @param properties         the list of property model generators for the entity's properties
     * @return the emitted entity model generator
     */
    public EntityModelGenerator entityModel(Class<?> type, CritterClassLoader critterClassLoader,
            ClassModel classModel, List<PropertyModelGenerator> properties) {
        return new EntityModelGenerator(mapper, type, critterClassLoader, properties).emit();
    }
}
