package dev.morphia.critter.parser.generator;

import java.lang.annotation.Annotation;
import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.MethodTypeDesc;
import java.lang.reflect.Modifier;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import dev.morphia.annotations.Entity;
import dev.morphia.critter.CritterClassLoader;
import dev.morphia.mapping.Mapper;
import dev.morphia.mapping.codec.pojo.PropertyModel;
import dev.morphia.mapping.codec.pojo.critter.CritterEntityModel;

import io.github.dmlloyd.classfile.ClassFile;

/**
 * Generates a ClassFile-based {@code CritterEntityModel} implementation for a Morphia entity class.
 */
public class EntityModelGenerator extends BaseGenerator {
    private final Mapper mapper;
    private final List<PropertyModelGenerator> properties;
    private final Entity entityAnnotation;
    private final List<Annotation> morphiaAnnotations;

    /**
     * Creates a new entity model generator for the given entity.
     *
     * @param mapper             the Morphia mapper
     * @param type               the entity class annotated with {@code @Entity}
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param properties         the property model generators for each of the entity's properties
     * @throws IllegalStateException if the entity class does not have an {@code @Entity} annotation
     */
    public EntityModelGenerator(Mapper mapper, Class<?> type, CritterClassLoader critterClassLoader,
            List<PropertyModelGenerator> properties) {
        super(type, critterClassLoader);
        this.mapper = mapper;
        this.properties = properties;
        generatedType = "%s.%sEntityModel".formatted(baseName, type.getSimpleName());

        Entity ann = type.getAnnotation(Entity.class);
        if (ann == null) {
            throw new IllegalStateException("Class %s does not have @Entity annotation".formatted(type.getName()));
        }
        this.entityAnnotation = ann;

        // Collect morphia annotations from this class and ancestors (de-duplicated)
        Set<String> registered = new LinkedHashSet<>();
        List<Annotation> allAnnotations = new java.util.ArrayList<>();
        Class<?> current = type;
        while (current != null && current != Object.class) {
            for (Annotation a : current.getAnnotations()) {
                if (a.annotationType().getName().startsWith("dev.morphia.annotations.")
                        && registered.add(a.annotationType().getName())) {
                    allAnnotations.add(a);
                }
            }
            current = current.getSuperclass();
        }
        this.morphiaAnnotations = List.copyOf(allAnnotations);
    }

    /**
     * Returns the annotation of the given type from the entity class, or {@code null} if not present.
     */
    @SuppressWarnings("unchecked")
    public <T extends Annotation> T annotation(Class<T> type) {
        return entity.getAnnotation(type);
    }

    /**
     * Returns the fully-qualified name of the generated entity model class.
     */
    public String getGeneratedType() {
        return generatedType;
    }

    /**
     * Emits the generated entity model class and returns this generator.
     */
    public EntityModelGenerator emit() {
        ClassDesc thisDesc = ClassDesc.of(generatedType);
        ClassDesc superDesc = ClassDesc.of(CritterEntityModel.class.getName());
        ClassDesc mapperDesc = ClassDesc.of(Mapper.class.getName());
        ClassDesc entityModelDesc = ClassDesc.of(dev.morphia.mapping.codec.pojo.EntityModel.class.getName());
        ClassDesc propertyModelDesc = ClassDesc.of(PropertyModel.class.getName());
        ClassDesc annotationDesc = ClassDesc.of(Annotation.class.getName());
        String collectionNameStr = computeCollectionName();
        String discriminatorStr = computeDiscriminator();
        String discriminatorKeyStr = computeDiscriminatorKey();
        boolean isAbstractFlag = Modifier.isAbstract(entity.getModifiers());
        boolean isInterfaceFlag = entity.isInterface();
        boolean useDiscriminatorFlag = entityAnnotation.useDiscriminator();

        byte[] bytes = ClassFile.of().build(thisDesc, cb -> {
            cb.withVersion(ClassFile.JAVA_17_VERSION, 0);
            cb.withFlags(ClassFile.ACC_PUBLIC | ClassFile.ACC_SUPER);
            cb.withSuperclass(superDesc);

            // Constructor: (Mapper) -> void
            cb.withMethodBody("<init>", MethodTypeDesc.of(ConstantDescs.CD_void, mapperDesc),
                    ClassFile.ACC_PUBLIC, cod -> {
                        cod.aload(0);
                        cod.aload(1);
                        GenerationUtils.emitClassRef(cod, entity);
                        cod.invokespecial(superDesc, "<init>",
                                MethodTypeDesc.of(ConstantDescs.CD_void, mapperDesc, ConstantDescs.CD_Class));

                        // setType(entityClass)
                        cod.aload(0);
                        GenerationUtils.emitClassRef(cod, entity);
                        cod.invokevirtual(thisDesc, "setType",
                                MethodTypeDesc.of(ConstantDescs.CD_void, ConstantDescs.CD_Class));

                        // Add property models
                        for (PropertyModelGenerator prop : properties) {
                            ClassDesc propDesc = ClassDesc.of(prop.generatedType);
                            cod.aload(0);
                            cod.new_(propDesc);
                            cod.dup();
                            cod.aload(0);
                            cod.invokespecial(propDesc, "<init>",
                                    MethodTypeDesc.of(ConstantDescs.CD_void, entityModelDesc));
                            cod.invokevirtual(entityModelDesc, "addProperty",
                                    MethodTypeDesc.of(ConstantDescs.CD_boolean, propertyModelDesc));
                            cod.pop();
                        }

                        // Morphia annotations via builders — no reflection
                        for (Annotation ann : morphiaAnnotations) {
                            cod.aload(0);
                            GenerationUtils.emitAnnotationViaBuilder(cod, ann);
                            cod.invokevirtual(entityModelDesc, "annotation",
                                    MethodTypeDesc.of(ConstantDescs.CD_void, annotationDesc));
                        }

                        // configureProperties(mapper)
                        cod.aload(0);
                        cod.aload(1);
                        cod.invokevirtual(thisDesc, "configureProperties",
                                MethodTypeDesc.of(ConstantDescs.CD_void, mapperDesc));

                        cod.return_();
                    });

            // collectionName(): String
            cb.withMethodBody("collectionName", MethodTypeDesc.of(ConstantDescs.CD_String),
                    ClassFile.ACC_PUBLIC, cod -> {
                        cod.ldc(collectionNameStr);
                        cod.areturn();
                    });

            // discriminator(): String
            cb.withMethodBody("discriminator", MethodTypeDesc.of(ConstantDescs.CD_String),
                    ClassFile.ACC_PUBLIC, cod -> {
                        cod.ldc(discriminatorStr);
                        cod.areturn();
                    });

            // discriminatorKey(): String
            cb.withMethodBody("discriminatorKey", MethodTypeDesc.of(ConstantDescs.CD_String),
                    ClassFile.ACC_PUBLIC, cod -> {
                        cod.ldc(discriminatorKeyStr);
                        cod.areturn();
                    });

            // isAbstract(): boolean
            GenerationUtils.emitBooleanMethod(cb, "isAbstract", isAbstractFlag);
            // isInterface(): boolean
            GenerationUtils.emitBooleanMethod(cb, "isInterface", isInterfaceFlag);
            // useDiscriminator(): boolean
            GenerationUtils.emitBooleanMethod(cb, "useDiscriminator", useDiscriminatorFlag);
        });

        critterClassLoader.register(generatedType, bytes);
        return this;
    }

    private String computeCollectionName() {
        String key = entityAnnotation.value();
        return Mapper.IGNORED_FIELDNAME.equals(key)
                ? mapper.getConfig().collectionNaming().apply(entity.getSimpleName())
                : key;
    }

    private String computeDiscriminator() {
        return mapper.getConfig().discriminator().apply(entity, entityAnnotation.discriminator());
    }

    private String computeDiscriminatorKey() {
        String key = entityAnnotation.discriminatorKey();
        return Mapper.IGNORED_FIELDNAME.equals(key)
                ? mapper.getConfig().discriminatorKey()
                : key;
    }

}
