package dev.morphia.critter.parser.generator;

import java.lang.constant.ClassDesc;
import java.lang.constant.ConstantDescs;
import java.lang.constant.MethodTypeDesc;
import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.invoke.VarHandle;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.Map;

import dev.morphia.critter.Critter;
import dev.morphia.critter.CritterClassLoader;
import dev.morphia.critter.parser.ExtensionFunctions;
import dev.morphia.critter.parser.FieldInfo;
import dev.morphia.critter.parser.MethodInfo;

import io.github.dmlloyd.classfile.ClassFile;
import io.github.dmlloyd.classfile.ClassSignature;
import io.github.dmlloyd.classfile.TypeKind;
import io.github.dmlloyd.classfile.attribute.SignatureAttribute;

/**
 * Generates a ClassFile-based {@link org.bson.codecs.pojo.PropertyAccessor} implementation that uses
 * {@link java.lang.invoke.VarHandle} (for fields) or {@link java.lang.invoke.MethodHandle} (for getter/setter pairs)
 * to access a single property of a Morphia entity class.
 */
public class VarHandleAccessorGenerator extends BaseGenerator {
    private static final Map<String, Class<?>> PRIMITIVE_CLASSES = Map.of(
            "boolean", boolean.class,
            "byte", byte.class,
            "char", char.class,
            "short", short.class,
            "int", int.class,
            "long", long.class,
            "float", float.class,
            "double", double.class);

    private final String propertyName;
    private final String propertyType;
    private final boolean isFieldBased;
    private final boolean isFinalField;
    private final String getterName;
    private final String setterName;

    /**
     * Creates a generator for a field-based property accessor using a {@link java.lang.invoke.VarHandle}.
     *
     * @param entity             the entity class that owns the field
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param field              the field info representing the property
     */
    public VarHandleAccessorGenerator(Class<?> entity, CritterClassLoader critterClassLoader, FieldInfo field) {
        super(entity, critterClassLoader);
        this.propertyName = field.name();
        this.propertyType = GenerationUtils.typeClassName(ClassDesc.ofDescriptor(field.desc()));
        this.isFieldBased = true;
        this.isFinalField = (field.access() & ClassFile.ACC_FINAL) != 0;
        this.getterName = null;
        this.setterName = null;
        generatedType = "%s.%sAccessor".formatted(baseName, Critter.titleCase(propertyName));
    }

    /**
     * Creates a generator for a method-based property accessor using {@link java.lang.invoke.MethodHandle}s.
     *
     * @param entity             the entity class that owns the getter
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param method             the method info representing the getter
     */
    public VarHandleAccessorGenerator(Class<?> entity, CritterClassLoader critterClassLoader, MethodInfo method) {
        super(entity, critterClassLoader);
        this.propertyName = ExtensionFunctions.getterToPropertyName(method, entity);
        String returnDesc = java.lang.constant.MethodTypeDesc.ofDescriptor(method.desc()).returnType().descriptorString();
        this.propertyType = GenerationUtils.typeClassName(ClassDesc.ofDescriptor(returnDesc));
        this.isFieldBased = false;
        this.isFinalField = false;
        this.getterName = method.name();
        this.setterName = "set%s".formatted(Critter.titleCase(propertyName));
        generatedType = "%s.%sAccessor".formatted(baseName, Critter.titleCase(propertyName));
    }

    /**
     * Returns {@code true} if the property type is a Java primitive.
     *
     * @return {@code true} if the property type is primitive
     */
    public boolean isPrimitive() {
        return GenerationUtils.PRIMITIVE_TO_WRAPPER.containsKey(propertyType);
    }

    /**
     * Returns the fully-qualified name of the wrapper class for the property type,
     * or the property type itself if it is not a primitive.
     *
     * @return the wrapper type name
     */
    public String getWrapperType() {
        return GenerationUtils.PRIMITIVE_TO_WRAPPER.getOrDefault(propertyType, propertyType);
    }

    private boolean hasSetter() {
        if (isFieldBased || setterName == null)
            return false;
        Class<?> paramClass = isPrimitive() ? PRIMITIVE_CLASSES.get(propertyType) : null;
        if (paramClass == null) {
            try {
                paramClass = Class.forName(propertyType, false, entityClassLoader());
            } catch (ClassNotFoundException e) {
                return false;
            }
        }
        Class<?> current = entity;
        while (current != null && current != Object.class) {
            try {
                Method m = current.getDeclaredMethod(setterName, paramClass);
                if (!Modifier.isPrivate(m.getModifiers()) && !Modifier.isStatic(m.getModifiers())) {
                    return true;
                }
            } catch (NoSuchMethodException e) {
                // walk up to superclass
            }
            current = current.getSuperclass();
        }
        return false;
    }

    /**
     * Emits the generated property accessor class and returns this generator.
     *
     * @return this generator after emitting
     */
    public VarHandleAccessorGenerator emit() {
        ClassDesc thisDesc = ClassDesc.of(generatedType);
        ClassDesc accessorDesc = ClassDesc.of("org.bson.codecs.pojo.PropertyAccessor");
        ClassDesc propertyDesc = propertyClassDesc();
        ClassDesc wrapperDesc = ClassDesc.of(getWrapperType());

        ClassDesc varHandleDesc = ClassDesc.of(VarHandle.class.getName());
        ClassDesc methodHandleDesc = ClassDesc.of(MethodHandle.class.getName());
        ClassDesc methodHandlesDesc = ClassDesc.of(MethodHandles.class.getName());
        ClassDesc lookupDesc = ClassDesc.of(MethodHandles.Lookup.class.getName());
        ClassDesc methodTypeDesc2 = ClassDesc.of(MethodType.class.getName());
        ClassDesc roeDesc = ClassDesc.of(ReflectiveOperationException.class.getName());
        ClassDesc rteDesc = ClassDesc.of(RuntimeException.class.getName());

        boolean useVarHandle = isFieldBased;
        boolean useSetterHandle = !isFieldBased && hasSetter();

        byte[] bytes = ClassFile.of().build(thisDesc, cb -> {
            cb.withVersion(ClassFile.JAVA_17_VERSION, 0);
            cb.withFlags(ClassFile.ACC_PUBLIC | ClassFile.ACC_SUPER);
            cb.withSuperclass(ConstantDescs.CD_Object);
            cb.withInterfaceSymbols(accessorDesc);

            // Class signature: implements PropertyAccessor<WrapperType>
            String wrapperInternalName = getWrapperType().replace('.', '/');
            String accInternal = "org/bson/codecs/pojo/PropertyAccessor";
            String wrapperTypeArg = wrapperInternalName.startsWith("[")
                    ? wrapperInternalName
                    : "L" + wrapperInternalName + ";";
            String sigStr = "Ljava/lang/Object;L" + accInternal + "<" + wrapperTypeArg + ">" + ";";
            cb.with(SignatureAttribute.of(ClassSignature.parseFrom(sigStr)));

            // Field: varHandle or getterHandle
            if (useVarHandle) {
                cb.withField("varHandle", varHandleDesc, ClassFile.ACC_PRIVATE | ClassFile.ACC_FINAL);
            } else {
                cb.withField("getterHandle", methodHandleDesc, ClassFile.ACC_PRIVATE | ClassFile.ACC_FINAL);
                if (useSetterHandle) {
                    cb.withField("setterHandle", methodHandleDesc, ClassFile.ACC_PRIVATE | ClassFile.ACC_FINAL);
                }
            }

            // Constructor
            cb.withMethodBody("<init>", MethodTypeDesc.ofDescriptor("()V"), ClassFile.ACC_PUBLIC, cod -> {
                cod.aload(0);
                cod.invokespecial(ConstantDescs.CD_Object, "<init>", MethodTypeDesc.ofDescriptor("()V"));

                // try { ... } catch (ReflectiveOperationException e) { throw new RuntimeException(e); }
                cod.trying(tryBody -> {
                    // MethodHandles.lookup()
                    tryBody.invokestatic(methodHandlesDesc, "lookup",
                            MethodTypeDesc.of(lookupDesc));
                    int callerLookupSlot = tryBody.allocateLocal(TypeKind.REFERENCE);
                    tryBody.astore(callerLookupSlot);

                    // Thread.currentThread().getContextClassLoader()
                    tryBody.invokestatic(ClassDesc.of("java.lang.Thread"), "currentThread",
                            MethodTypeDesc.of(ClassDesc.of("java.lang.Thread")));
                    tryBody.invokevirtual(ClassDesc.of("java.lang.Thread"), "getContextClassLoader",
                            MethodTypeDesc.of(ClassDesc.of("java.lang.ClassLoader")));
                    int tcclSlot = tryBody.allocateLocal(TypeKind.REFERENCE);
                    tryBody.astore(tcclSlot);

                    // Class.forName(entityName, true, tccl)
                    tryBody.ldc(entity.getName());
                    tryBody.iconst_1();
                    tryBody.aload(tcclSlot);
                    tryBody.invokestatic(ConstantDescs.CD_Class, "forName",
                            MethodTypeDesc.ofDescriptor("(Ljava/lang/String;ZLjava/lang/ClassLoader;)Ljava/lang/Class;"));
                    int entityClassSlot = tryBody.allocateLocal(TypeKind.REFERENCE);
                    tryBody.astore(entityClassSlot);

                    // MethodHandles.privateLookupIn(entityClass, callerLookup)
                    tryBody.aload(entityClassSlot);
                    tryBody.aload(callerLookupSlot);
                    tryBody.invokestatic(methodHandlesDesc, "privateLookupIn",
                            MethodTypeDesc.of(lookupDesc, ConstantDescs.CD_Class, lookupDesc));
                    int privateLookupSlot = tryBody.allocateLocal(TypeKind.REFERENCE);
                    tryBody.astore(privateLookupSlot);

                    if (useVarHandle) {
                        // privateLookup.findVarHandle(entityClass, fieldName, fieldType)
                        tryBody.aload(privateLookupSlot);
                        tryBody.aload(entityClassSlot);
                        tryBody.ldc(propertyName);
                        emitLoadClass(tryBody, propertyType, propertyDesc, tcclSlot);
                        tryBody.invokevirtual(lookupDesc, "findVarHandle",
                                MethodTypeDesc.of(varHandleDesc, ConstantDescs.CD_Class, ConstantDescs.CD_String, ConstantDescs.CD_Class));
                        tryBody.aload(0);
                        tryBody.swap();
                        tryBody.putfield(thisDesc, "varHandle", varHandleDesc);
                    } else {
                        // privateLookup.findVirtual(entityClass, getterName, MethodType.methodType(returnType))
                        tryBody.aload(privateLookupSlot);
                        tryBody.aload(entityClassSlot);
                        tryBody.ldc(getterName);
                        emitLoadClass(tryBody, propertyType, propertyDesc, tcclSlot);
                        tryBody.invokestatic(methodTypeDesc2, "methodType",
                                MethodTypeDesc.of(methodTypeDesc2, ConstantDescs.CD_Class));
                        tryBody.invokevirtual(lookupDesc, "findVirtual",
                                MethodTypeDesc.of(methodHandleDesc, ConstantDescs.CD_Class, ConstantDescs.CD_String, methodTypeDesc2));
                        tryBody.aload(0);
                        tryBody.swap();
                        tryBody.putfield(thisDesc, "getterHandle", methodHandleDesc);

                        if (useSetterHandle) {
                            // privateLookup.findVirtual(entityClass, setterName, MethodType.methodType(void.class, paramType))
                            tryBody.aload(privateLookupSlot);
                            tryBody.aload(entityClassSlot);
                            tryBody.ldc(setterName);
                            tryBody.loadConstant(ConstantDescs.CD_void);
                            emitLoadClass(tryBody, propertyType, propertyDesc, tcclSlot);
                            tryBody.invokestatic(methodTypeDesc2, "methodType",
                                    MethodTypeDesc.of(methodTypeDesc2, ConstantDescs.CD_Class, ConstantDescs.CD_Class));
                            tryBody.invokevirtual(lookupDesc, "findVirtual",
                                    MethodTypeDesc.of(methodHandleDesc, ConstantDescs.CD_Class, ConstantDescs.CD_String, methodTypeDesc2));
                            tryBody.aload(0);
                            tryBody.swap();
                            tryBody.putfield(thisDesc, "setterHandle", methodHandleDesc);
                        }
                    }
                    tryBody.return_();
                }, catches -> catches.catching(roeDesc, catchBody -> {
                    catchBody.astore(1);
                    catchBody.new_(rteDesc);
                    catchBody.dup();
                    catchBody.aload(1);
                    catchBody.invokespecial(rteDesc, "<init>",
                            MethodTypeDesc.ofDescriptor("(Ljava/lang/Throwable;)V"));
                    catchBody.athrow();
                }));
            });

            // get(Object model): Object
            cb.withMethodBody("get", MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;)Ljava/lang/Object;"),
                    ClassFile.ACC_PUBLIC, cod -> {
                        // null check
                        cod.aload(1);
                        var label = cod.newLabel();
                        cod.ifnonnull(label);
                        cod.aconst_null();
                        cod.areturn();
                        cod.labelBinding(label);

                        if (useVarHandle) {
                            cod.aload(0);
                            cod.getfield(thisDesc, "varHandle", varHandleDesc);
                            cod.aload(1);
                            cod.invokevirtual(varHandleDesc, "get",
                                    MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;)Ljava/lang/Object;"));
                        } else {
                            cod.aload(0);
                            cod.getfield(thisDesc, "getterHandle", methodHandleDesc);
                            cod.aload(1);
                            cod.invokevirtual(methodHandleDesc, "invoke",
                                    MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;)Ljava/lang/Object;"));
                        }
                        if (isPrimitive()) {
                            cod.checkcast(wrapperDesc);
                        }
                        cod.areturn();
                    });

            // set(Object model, Object value): void
            cb.withMethodBody("set", MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;Ljava/lang/Object;)V"),
                    ClassFile.ACC_PUBLIC, cod -> {
                        if (!isFieldBased && !useSetterHandle) {
                            cod.new_(ClassDesc.of("java.lang.UnsupportedOperationException"));
                            cod.dup();
                            cod.ldc("Property '%s' is read-only".formatted(propertyName));
                            cod.invokespecial(ClassDesc.of("java.lang.UnsupportedOperationException"), "<init>",
                                    MethodTypeDesc.ofDescriptor("(Ljava/lang/String;)V"));
                            cod.athrow();
                            return;
                        }

                        if (isFinalField) {
                            // Use reflection to set final field
                            ClassDesc fieldDesc2 = ClassDesc.of("java.lang.reflect.Field");
                            cod.trying(tryBody -> {
                                GenerationUtils.emitClassRef(tryBody, entity);
                                tryBody.ldc(propertyName);
                                tryBody.invokevirtual(ConstantDescs.CD_Class, "getDeclaredField",
                                        MethodTypeDesc.of(fieldDesc2, ConstantDescs.CD_String));
                                int fieldSlot = tryBody.allocateLocal(TypeKind.REFERENCE);
                                tryBody.astore(fieldSlot);
                                tryBody.aload(fieldSlot);
                                tryBody.iconst_1();
                                tryBody.invokevirtual(fieldDesc2, "setAccessible",
                                        MethodTypeDesc.ofDescriptor("(Z)V"));
                                tryBody.aload(fieldSlot);
                                tryBody.aload(1);
                                tryBody.aload(2);
                                tryBody.invokevirtual(fieldDesc2, "set",
                                        MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;Ljava/lang/Object;)V"));
                                tryBody.return_();
                            }, catches -> catches.catching(ClassDesc.of("java.lang.Exception"), catchBody -> {
                                catchBody.astore(3);
                                catchBody.new_(rteDesc);
                                catchBody.dup();
                                catchBody.ldc("Failed to set final field '%s'".formatted(propertyName));
                                catchBody.invokespecial(rteDesc, "<init>",
                                        MethodTypeDesc.ofDescriptor("(Ljava/lang/String;)V"));
                                catchBody.athrow();
                            }));
                            return;
                        }

                        if (useVarHandle) {
                            cod.aload(0);
                            cod.getfield(thisDesc, "varHandle", varHandleDesc);
                            cod.aload(1);
                            cod.aload(2);
                            if (isPrimitive()) {
                                cod.checkcast(wrapperDesc);
                                cod.invokevirtual(wrapperDesc, primitiveUnboxMethod(),
                                        MethodTypeDesc.of(propertyDesc));
                                cod.invokevirtual(varHandleDesc, "set",
                                        MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;" + propertyDesc.descriptorString() + ")V"));
                            } else {
                                // skip checkcast: VarHandle.set(Object,Object) accepts Object;
                                // checkcast to a non-public inner class would cause IllegalAccessError
                                cod.invokevirtual(varHandleDesc, "set",
                                        MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;Ljava/lang/Object;)V"));
                            }
                        } else {
                            cod.aload(0);
                            cod.getfield(thisDesc, "setterHandle", methodHandleDesc);
                            cod.aload(1);
                            cod.aload(2);
                            if (isPrimitive()) {
                                cod.checkcast(wrapperDesc);
                                cod.invokevirtual(wrapperDesc, primitiveUnboxMethod(),
                                        MethodTypeDesc.of(propertyDesc));
                                cod.invokevirtual(methodHandleDesc, "invoke",
                                        MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;" + propertyDesc.descriptorString() + ")V"));
                            } else {
                                // skip checkcast: MethodHandle.invoke(Object,Object) accepts Object;
                                // checkcast to a non-public inner class would cause IllegalAccessError
                                cod.invokevirtual(methodHandleDesc, "invoke",
                                        MethodTypeDesc.ofDescriptor("(Ljava/lang/Object;Ljava/lang/Object;)V"));
                            }
                        }
                        cod.return_();
                    });
        });

        critterClassLoader.register(generatedType, bytes);
        return this;
    }

    private void emitLoadClass(io.github.dmlloyd.classfile.CodeBuilder cod, String typeName, ClassDesc desc,
            int tcclSlot) {
        if (isPrimitive()) {
            cod.loadConstant(desc);
        } else {
            // Emit Class.forName(typeName, false, tccl) so the property type is resolved via the
            // same classloader used to load the entity, not the accessor's defining classloader.
            cod.ldc(typeName);
            cod.iconst_0();
            cod.aload(tcclSlot);
            cod.invokestatic(ConstantDescs.CD_Class, "forName",
                    MethodTypeDesc.ofDescriptor("(Ljava/lang/String;ZLjava/lang/ClassLoader;)Ljava/lang/Class;"));
        }
    }

    private ClassLoader entityClassLoader() {
        return GenerationUtils.safeClassLoader(entity);
    }

    private ClassDesc propertyClassDesc() {
        if (isPrimitive()) {
            return switch (propertyType) {
                case "boolean" -> ConstantDescs.CD_boolean;
                case "byte" -> ConstantDescs.CD_byte;
                case "char" -> ConstantDescs.CD_char;
                case "short" -> ConstantDescs.CD_short;
                case "int" -> ConstantDescs.CD_int;
                case "long" -> ConstantDescs.CD_long;
                case "float" -> ConstantDescs.CD_float;
                case "double" -> ConstantDescs.CD_double;
                default -> throw new IllegalArgumentException("Not a primitive: " + propertyType);
            };
        }
        if (propertyType.startsWith("[")) {
            return ClassDesc.ofDescriptor(propertyType.replace('.', '/'));
        }
        return ClassDesc.of(propertyType);
    }

    private String primitiveUnboxMethod() {
        return switch (propertyType) {
            case "boolean" -> "booleanValue";
            case "byte" -> "byteValue";
            case "char" -> "charValue";
            case "short" -> "shortValue";
            case "int" -> "intValue";
            case "long" -> "longValue";
            case "float" -> "floatValue";
            case "double" -> "doubleValue";
            default -> throw new IllegalArgumentException("Not a primitive: " + propertyType);
        };
    }
}
