package dev.morphia.critter.parser.gizmo;

import java.io.IOException;
import java.util.List;

import dev.morphia.critter.CritterClassLoader;
import dev.morphia.critter.parser.Generators;
import dev.morphia.critter.parser.PropertyFinder;
import dev.morphia.critter.parser.asm.AddFieldAccessorMethods;
import dev.morphia.critter.parser.asm.AddMethodAccessorMethods;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.MethodNode;

/**
 * Facade that orchestrates the full Gizmo-based code generation pipeline for a Morphia entity,
 * including field/method accessor injection and property/entity model generation.
 */
public class CritterGizmoGenerator {
    private final Generators generators;

    /**
     * Creates a new CritterGizmoGenerator with the given Generators instance.
     *
     * @param generators the shared Generators providing config and mapper
     */
    public CritterGizmoGenerator(Generators generators) {
        this.generators = generators;
    }

    /**
     * Reads the entity class bytecode, discovers its properties, and generates all required Critter support classes.
     *
     * @param type               the entity class to process
     * @param critterClassLoader the class loader that will receive generated bytecode
     * @param runtimeMode        {@code true} to generate VarHandle-based accessors for runtime use
     * @return the generated entity model generator
     */
    public GizmoEntityModelGenerator generate(Class<?> type, CritterClassLoader critterClassLoader, boolean runtimeMode) {
        ClassNode classNode = new ClassNode();
        String resourceName = "%s.class".formatted(type.getName().replace('.', '/'));
        java.io.InputStream inputStream = type.getClassLoader().getResourceAsStream(resourceName);
        if (inputStream == null) {
            throw new IllegalArgumentException("Could not find class file for %s".formatted(type.getName()));
        }
        try {
            new ClassReader(inputStream).accept(classNode, 0);
        } catch (IOException e) {
            throw new RuntimeException("Failed to read class %s".formatted(type.getName()), e);
        }
        PropertyFinder propertyFinder = new PropertyFinder(generators, critterClassLoader, runtimeMode);

        return entityModel(type, critterClassLoader, classNode, propertyFinder.find(type, classNode));
    }

    /**
     * Reads the entity class bytecode, discovers its properties, and generates all required Critter support classes
     * using build-time (non-runtime) mode.
     *
     * @param type               the entity class to process
     * @param critterClassLoader the class loader that will receive generated bytecode
     * @return the generated entity model generator
     */
    public GizmoEntityModelGenerator generate(Class<?> type, CritterClassLoader critterClassLoader) {
        return generate(type, critterClassLoader, false);
    }

    /**
     * Generates bytecode augmenting the entity with synthetic {@code __readXxx}/{@code __writeXxx} methods for its fields.
     *
     * @param entityType the entity class to augment
     * @param fields     the fields for which accessor methods should be generated
     * @return the augmented class bytecode
     */
    public byte[] fieldAccessors(Class<?> entityType, List<FieldNode> fields) {
        return new AddFieldAccessorMethods(entityType, fields).emit();
    }

    /**
     * Generates bytecode augmenting the entity with synthetic {@code __readXxx}/{@code __writeXxx} methods for its getter methods.
     *
     * @param entityType the entity class to augment
     * @param methods    the getter methods for which accessor methods should be generated
     * @return the augmented class bytecode
     */
    public byte[] methodAccessors(Class<?> entityType, List<MethodNode> methods) {
        return new AddMethodAccessorMethods(entityType, methods).emit();
    }

    /**
     * Generates and registers a {@link PropertyAccessorGenerator} for the given field.
     *
     * @param entityType         the entity class that owns the field
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param field              the field for which a property accessor should be generated
     * @return the emitted property accessor generator
     */
    public PropertyAccessorGenerator propertyAccessor(Class<?> entityType, CritterClassLoader critterClassLoader, FieldNode field) {
        return new PropertyAccessorGenerator(entityType, critterClassLoader, field).emit();
    }

    /**
     * Generates and registers a {@link PropertyAccessorGenerator} for the given getter method.
     *
     * @param entityType         the entity class that owns the method
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param method             the getter method for which a property accessor should be generated
     * @return the emitted property accessor generator
     */
    public PropertyAccessorGenerator propertyAccessor(Class<?> entityType, CritterClassLoader critterClassLoader, MethodNode method) {
        return new PropertyAccessorGenerator(entityType, critterClassLoader, method).emit();
    }

    /**
     * Generates and registers a VarHandle-based accessor for the given field (used in runtime mode).
     *
     * @param entityType         the entity class that owns the field
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param field              the field for which a VarHandle accessor should be generated
     * @return the emitted VarHandle accessor generator
     */
    public VarHandleAccessorGenerator varHandleAccessor(Class<?> entityType, CritterClassLoader critterClassLoader, FieldNode field) {
        return new VarHandleAccessorGenerator(entityType, critterClassLoader, field).emit();
    }

    /**
     * Generates and registers a VarHandle-based accessor for the property exposed by the given getter method (used in runtime mode).
     *
     * @param entityType         the entity class that owns the method
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param method             the getter method for which a VarHandle accessor should be generated
     * @return the emitted VarHandle accessor generator
     */
    public VarHandleAccessorGenerator varHandleAccessor(Class<?> entityType, CritterClassLoader critterClassLoader, MethodNode method) {
        return new VarHandleAccessorGenerator(entityType, critterClassLoader, method).emit();
    }

    /**
     * Generates and registers a {@link PropertyModelGenerator} for the given field.
     *
     * @param entityType         the entity class that owns the field
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param field              the field for which a property model should be generated
     * @return the emitted property model generator
     */
    public PropertyModelGenerator propertyModelGenerator(Class<?> entityType, CritterClassLoader critterClassLoader, FieldNode field) {
        return new PropertyModelGenerator(generators.getMapper().getConfig(), entityType, critterClassLoader, field).emit();
    }

    /**
     * Generates and registers a {@link PropertyModelGenerator} for the property exposed by the given getter method.
     *
     * @param entityType         the entity class that owns the method
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param method             the getter method for which a property model should be generated
     * @return the emitted property model generator
     */
    public PropertyModelGenerator propertyModelGenerator(Class<?> entityType, CritterClassLoader critterClassLoader, MethodNode method) {
        return new PropertyModelGenerator(generators.getMapper().getConfig(), entityType, critterClassLoader, method).emit();
    }

    /**
     * Generates and registers the entity model class for the given type.
     *
     * @param type               the entity class
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param classNode          the ASM class node for the entity
     * @param properties         the list of property model generators for the entity's properties
     * @return the emitted entity model generator
     */
    public GizmoEntityModelGenerator entityModel(Class<?> type, CritterClassLoader critterClassLoader,
            ClassNode classNode, List<PropertyModelGenerator> properties) {
        return new GizmoEntityModelGenerator(generators, type, critterClassLoader, classNode, properties).emit();
    }
}
