package dev.morphia.critter.parser.gizmo;

import java.io.IOException;
import java.io.InputStream;
import java.lang.annotation.Annotation;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import dev.morphia.annotations.Entity;
import dev.morphia.annotations.internal.AnnotationNodeExtensions;
import dev.morphia.critter.CritterClassLoader;
import dev.morphia.mapping.Mapper;
import dev.morphia.mapping.codec.pojo.EntityModel;
import dev.morphia.mapping.codec.pojo.PropertyModel;
import dev.morphia.mapping.codec.pojo.critter.CritterEntityModel;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.tree.AnnotationNode;
import org.objectweb.asm.tree.ClassNode;

import io.quarkus.gizmo.MethodCreator;
import io.quarkus.gizmo.MethodDescriptor;

import static io.quarkus.gizmo.MethodDescriptor.ofMethod;

/**
 * Generates a Gizmo-based {@code CritterEntityModel} implementation for a Morphia entity class.
 */
public class GizmoEntityModelGenerator extends BaseGizmoGenerator {
    private final Mapper mapper;
    private final ClassNode classNode;
    private final List<PropertyModelGenerator> properties;
    private final List<AnnotationNode> annotations;
    private final List<Annotation> morphiaAnnotations;
    private final Entity entityAnnotation;

    /**
     * Creates a new entity model generator for the given entity.
     *
     * @param mapper             the Morphia mapper
     * @param type               the entity class annotated with {@code @Entity}
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param classNode          the ASM class node for the entity
     * @param properties         the property model generators for each of the entity's properties
     * @throws IllegalStateException if the entity class does not have an {@code @Entity} annotation
     */
    public GizmoEntityModelGenerator(Mapper mapper, Class<?> type, CritterClassLoader critterClassLoader,
            ClassNode classNode, List<PropertyModelGenerator> properties) {
        super(type, critterClassLoader);
        this.mapper = mapper;
        this.classNode = classNode;
        this.properties = properties;

        generatedType = "%s.%sEntityModel".formatted(baseName, type.getSimpleName());
        this.annotations = classNode.visibleAnnotations != null ? classNode.visibleAnnotations : Collections.emptyList();

        Entity ann = type.getAnnotation(Entity.class);
        if (ann == null) {
            throw new IllegalStateException("Class %s does not have @Entity annotation".formatted(type.getName()));
        }
        this.entityAnnotation = ann;

        this.morphiaAnnotations = new ArrayList<>();
        for (AnnotationNode a : annotations) {
            if (a.desc.startsWith("Ldev/morphia/annotations/")) {
                morphiaAnnotations.add((Annotation) AnnotationNodeExtensions.INSTANCE.toMorphiaAnnotation(a));
            }
        }
    }

    /**
     * Returns the annotation of the given type from the entity class, or {@code null} if not present.
     *
     * @param <T>  the annotation type
     * @param type the annotation class to look up
     * @return the annotation instance, or {@code null}
     */
    @SuppressWarnings("unchecked")
    public <T extends Annotation> T annotation(Class<T> type) {
        return entity.getAnnotation(type);
    }

    /**
     * Returns the fully-qualified name of the generated entity model class.
     *
     * @return the generated class name
     */
    public String getGeneratedType() {
        return generatedType;
    }

    /**
     * Emits the generated entity model class and returns this generator.
     *
     * @return this generator after emitting
     */
    public GizmoEntityModelGenerator emit() {
        getBuilder().superClass(CritterEntityModel.class);

        try (var creator = getCreator()) {
            ctor();
            collectionName();
            discriminator();
            discriminatorKey();
            hasLifecycle();
            isAbstract();
            isInterface();
            useDiscriminator();
        }

        return this;
    }

    private void useDiscriminator() {
        try (MethodCreator mc = getCreator().getMethodCreator("useDiscriminator", boolean.class)) {
            mc.returnValue(mc.load(entityAnnotation.useDiscriminator()));
        }
    }

    private void isInterface() {
        try (MethodCreator mc = getCreator().getMethodCreator("isInterface", boolean.class)) {
            mc.returnValue(mc.load(entity.isInterface()));
        }
    }

    private void hasLifecycle() {
        try (MethodCreator mc = getCreator().getMethodCreator("hasLifecycle", boolean.class, Class.class)) {
            mc.setParameterNames(new String[] { "type" });
            mc.returnValue(mc.load(false));
        }
    }

    private void isAbstract() {
        try (MethodCreator mc = getCreator().getMethodCreator("isAbstract", boolean.class)) {
            mc.returnValue(mc.load(Modifier.isAbstract(entity.getModifiers())));
        }
    }

    private void discriminatorKey() {
        try (MethodCreator mc = getCreator().getMethodCreator("discriminatorKey", String.class)) {
            String key = entityAnnotation.discriminator();
            String result = Mapper.IGNORED_FIELDNAME.equals(key)
                    ? mapper.getConfig().discriminatorKey()
                    : key;
            mc.returnValue(mc.load(result));
        }
    }

    private void discriminator() {
        try (MethodCreator mc = getCreator().getMethodCreator("discriminator", String.class)) {
            String discriminator = mapper.getConfig().discriminator()
                    .apply(entity, entityAnnotation.discriminator());
            mc.returnValue(mc.load(discriminator));
        }
    }

    private void collectionName() {
        try (MethodCreator mc = getCreator().getMethodCreator("collectionName", String.class)) {
            String key = entityAnnotation.value();
            String result = Mapper.IGNORED_FIELDNAME.equals(key)
                    ? mapper.getConfig().collectionNaming().apply(entity.getSimpleName())
                    : key;
            mc.returnValue(mc.load(result));
        }
    }

    private void ctor() {
        try (MethodCreator constructor = getCreator().getConstructorCreator(Mapper.class)) {
            constructor.invokeSpecialMethod(
                    MethodDescriptor.ofConstructor(CritterEntityModel.class, Mapper.class, Class.class),
                    constructor.getThis(),
                    constructor.getMethodParam(0),
                    constructor.loadClass(entity));
            constructor.setParameterNames(new String[] { "mapper" });

            constructor.invokeVirtualMethod(
                    ofMethod(generatedType, "setType", "void", Class.class),
                    constructor.getThis(),
                    constructor.loadClass(entity));
            loadProperties(constructor);
            registerAnnotations(constructor);
            constructor.invokeVirtualMethod(
                    ofMethod(generatedType, "configureProperties", "void", Mapper.class),
                    constructor.getThis(),
                    constructor.getMethodParam(0));
            constructor.returnVoid();
        }
    }

    private void loadProperties(MethodCreator creator) {
        MethodDescriptor addProperty = ofMethod(generatedType, "addProperty", "boolean", PropertyModel.class);
        for (PropertyModelGenerator property : properties) {
            MethodDescriptor modelCtor = MethodDescriptor.ofConstructor(property.generatedType, EntityModel.class);
            var model = creator.newInstance(modelCtor, creator.getThis());
            creator.invokeVirtualMethod(addProperty, creator.getThis(), model);
        }
    }

    private void registerAnnotations(MethodCreator constructor) {
        MethodDescriptor annotationMethod = ofMethod(generatedType, "annotation", "void", Annotation.class);
        Set<String> registered = new LinkedHashSet<>();

        // Register annotations directly on this class first
        for (AnnotationNode annotation : annotations) {
            if (registered.add(annotation.desc)) {
                constructor.invokeVirtualMethod(
                        annotationMethod,
                        constructor.getThis(),
                        GizmoExtensions.annotationBuilder(annotation, constructor));
            }
        }

        // Walk parent class hierarchy to register inherited annotations not on this class
        Class<?> parent = entity.getSuperclass();
        while (parent != null && !parent.equals(Object.class)) {
            String resourceName = "%s.class".formatted(parent.getName().replace('.', '/'));
            InputStream inputStream = parent.getClassLoader() != null
                    ? parent.getClassLoader().getResourceAsStream(resourceName)
                    : ClassLoader.getSystemResourceAsStream(resourceName);
            if (inputStream != null) {
                try {
                    ClassNode parentNode = new ClassNode();
                    new ClassReader(inputStream).accept(parentNode, 0);
                    if (parentNode.visibleAnnotations != null) {
                        for (AnnotationNode annotation : parentNode.visibleAnnotations) {
                            if (registered.add(annotation.desc)) {
                                constructor.invokeVirtualMethod(
                                        annotationMethod,
                                        constructor.getThis(),
                                        GizmoExtensions.annotationBuilder(annotation, constructor));
                            }
                        }
                    }
                } catch (IOException e) {
                    // skip if parent class bytecode can't be read
                }
            }
            parent = parent.getSuperclass();
        }
    }
}
