package dev.morphia.critter.parser.gizmo;

import java.util.Map;

import dev.morphia.critter.Critter;
import dev.morphia.critter.CritterClassLoader;
import dev.morphia.critter.parser.ExtensionFunctions;

import org.bson.codecs.pojo.PropertyAccessor;
import org.objectweb.asm.Type;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.MethodNode;

import io.quarkus.gizmo.MethodDescriptor;
import io.quarkus.gizmo.ResultHandle;

import static io.quarkus.gizmo.MethodDescriptor.ofConstructor;
import static io.quarkus.gizmo.MethodDescriptor.ofMethod;
import static io.quarkus.gizmo.SignatureBuilder.forClass;
import static io.quarkus.gizmo.SignatureBuilder.forMethod;
import static io.quarkus.gizmo.Type.classType;
import static io.quarkus.gizmo.Type.parameterizedType;
import static io.quarkus.gizmo.Type.typeVariable;
import static io.quarkus.gizmo.Type.voidType;

/**
 * Generates a Gizmo-based {@link org.bson.codecs.pojo.PropertyAccessor} implementation for a single
 * entity property, delegating to the synthetic {@code __readXxx}/{@code __writeXxx} methods.
 */
public class PropertyAccessorGenerator extends BaseGizmoGenerator {
    private static final Map<String, String> PRIMITIVE_TO_WRAPPER = Map.of(
            "boolean", "java.lang.Boolean",
            "byte", "java.lang.Byte",
            "char", "java.lang.Character",
            "short", "java.lang.Short",
            "int", "java.lang.Integer",
            "long", "java.lang.Long",
            "float", "java.lang.Float",
            "double", "java.lang.Double");

    private final String propertyName;
    private final String propertyType;

    /**
     * Creates a generator for a property accessor backed by a field.
     *
     * @param entity             the entity class that owns the field
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param field              the field representing the property
     */
    public PropertyAccessorGenerator(Class<?> entity, CritterClassLoader critterClassLoader, FieldNode field) {
        super(entity, critterClassLoader);
        this.propertyName = field.name;
        this.propertyType = Type.getType(field.desc).getClassName();
        generatedType = "%s.%sAccessor".formatted(baseName, Critter.titleCase(propertyName));
    }

    /**
     * Creates a generator for a property accessor backed by a getter method.
     *
     * @param entity             the entity class that owns the getter method
     * @param critterClassLoader the class loader that will receive the generated bytecode
     * @param method             the getter method representing the property
     */
    public PropertyAccessorGenerator(Class<?> entity, CritterClassLoader critterClassLoader, MethodNode method) {
        super(entity, critterClassLoader);
        this.propertyName = ExtensionFunctions.getterToPropertyName(method, entity);
        this.propertyType = Type.getReturnType(method.desc).getClassName();
        generatedType = "%s.%sAccessor".formatted(baseName, Critter.titleCase(propertyName));
    }

    /**
     * Returns {@code true} if the property type is a Java primitive type.
     *
     * @return {@code true} if the property type is primitive
     */
    public boolean isPrimitive() {
        return PRIMITIVE_TO_WRAPPER.containsKey(propertyType);
    }

    /**
     * Returns the fully-qualified name of the wrapper type for the property type,
     * or the property type itself if it is not primitive.
     *
     * @return the wrapper type name
     */
    public String getWrapperType() {
        return PRIMITIVE_TO_WRAPPER.getOrDefault(propertyType, propertyType);
    }

    /**
     * Emits the generated property accessor class and returns this generator.
     *
     * @return this generator after emitting
     */
    public PropertyAccessorGenerator emit() {
        getBuilder().signature(
                forClass()
                        .addInterface(
                                parameterizedType(
                                        classType(PropertyAccessor.class),
                                        classType(propertyType))));

        try (var creator = getCreator()) {
            ctor();
            get();
            set();
        }

        return this;
    }

    private void get() {
        var method = getCreator().getMethodCreator(
                ofMethod(generatedType, "get", Object.class.getName(), Object.class.getName()));
        method.setSignature(
                forMethod()
                        .addTypeParameter(typeVariable("S"))
                        .setReturnType(classType(propertyType))
                        .addParameterType(typeVariable("S"))
                        .build());
        method.setParameterNames(new String[] { "model" });
        ResultHandle castModel = method.checkCast(method.getMethodParam(0), entity);
        MethodDescriptor toInvoke = ofMethod(entity, "__read%s".formatted(Critter.titleCase(propertyName)), propertyType);
        ResultHandle result = method.invokeVirtualMethod(toInvoke, castModel);
        ResultHandle boxed = isPrimitive() ? method.smartCast(result, getWrapperType()) : result;
        method.returnValue(boxed);
    }

    private void set() {
        var method = getCreator().getMethodCreator(
                ofMethod(generatedType, "set", "void", Object.class.getName(), Object.class.getName()));
        method.setSignature(
                forMethod()
                        .addTypeParameter(typeVariable("S"))
                        .setReturnType(voidType())
                        .addParameterType(typeVariable("S"))
                        .addParameterType(classType(propertyType))
                        .build());
        method.setParameterNames(new String[] { "model", "value" });
        ResultHandle castModel = method.checkCast(method.getMethodParam(0), entity);
        ResultHandle castValue;
        if (isPrimitive()) {
            ResultHandle boxed = method.checkCast(method.getMethodParam(1), getWrapperType());
            castValue = method.smartCast(boxed, propertyType);
        } else {
            castValue = method.checkCast(method.getMethodParam(1), propertyType);
        }
        MethodDescriptor toInvoke = ofMethod(entity, "__write%s".formatted(Critter.titleCase(propertyName)), "void", propertyType);
        method.invokeVirtualMethod(toInvoke, castModel, castValue);
        method.returnValue(null);
    }

    private void ctor() {
        var constructor = getCreator().getConstructorCreator(new String[0]);
        constructor.invokeSpecialMethod(ofConstructor(Object.class), constructor.getThis());
        constructor.returnVoid();
        constructor.close();
    }
}
