package dev.morphia.critter.parser.gizmo;

import dev.morphia.critter.Critter;
import dev.morphia.critter.CritterClassLoader;

import io.quarkus.gizmo.ClassCreator;

/**
 * Base class for Gizmo-based code generators that produce Critter accessor and model classes.
 */
public abstract class BaseGizmoGenerator {
    /** The entity class for which code is being generated. */
    protected final Class<?> entity;
    /** The class loader used to register generated class bytecode. */
    protected final CritterClassLoader critterClassLoader;
    /** The fully-qualified name of the class being generated. */
    protected String generatedType;

    /** The base package name derived from the entity, used to namespace generated types. */
    protected final String baseName;

    private ClassCreator.Builder builder;
    private ClassCreator creator;

    /**
     * Creates a new generator for the given entity using the supplied class loader.
     *
     * @param entity             the entity class for which code will be generated
     * @param critterClassLoader the class loader that will receive generated bytecode
     */
    protected BaseGizmoGenerator(Class<?> entity, CritterClassLoader critterClassLoader) {
        this.entity = entity;
        this.critterClassLoader = critterClassLoader;
        this.baseName = Critter.critterPackage(entity);
    }

    /**
     * Returns the lazily created {@link ClassCreator.Builder} configured to output bytecode via the class loader.
     *
     * @return the class creator builder
     */
    protected ClassCreator.Builder getBuilder() {
        if (builder == null) {
            builder = ClassCreator.builder()
                    .classOutput((name, data) -> critterClassLoader.register(name.replace('/', '.'), data))
                    .className(generatedType);
        }
        return builder;
    }

    /**
     * Returns the lazily created {@link ClassCreator}, building it from the builder on first access.
     *
     * @return the class creator
     */
    protected ClassCreator getCreator() {
        if (creator == null) {
            creator = getBuilder().build();
        }
        return creator;
    }
}
