= Validation Extension

This is a simple extension to Morphia to process JSR 303 Validation Annotations.

== Using

Add this at the start of your application (or wherever you create your morphia instances).

[source,``java]
----
new ValidationExtension(morphia);
----

``

=== Example

Here is a simple example using (as an example) Hibernate validation:

[source,java]
----
...
import org.hibernate.validator.constraints.Email;
...

@Entity
public class Userlike {
	@Id ObjectId id;
	@Email String email;
}

----

== Implementation

This is a lightweight wrapper around the JSR 303 API. It installs a simple global entity interceptor which listens to all
xref:lifeCycleMethods.adoc[life cycle methods] needed for validation.
You can use any implementation of JSR 303 by just adding it to the classpath.

You can look at the code {srcRef}/validation/src/main/java/dev/morphia/ValidationExtension.java[here].

== Dependencies

=== Manual

- http://hibernate.org/validator/[Hibernate Validator]

=== Maven

If you use Maven to manage your project, you can reference Morphia as a dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>dev.morphia.morphia</groupId>
    <artifactId>validation</artifactId>
    <version>{version}</version>
</dependency>
----
