= GridFS Support

To effectively store GridFS components as entity fields, Morphia will need some extra information:

1. The optional bucket name
2. How to de/serialize the data

GridFS exposes a number of "knobs" to fine tune how GridFS items are stored but it's unclear how feasible it would be to expose those via Morphia APIs.
But before devling too deeply there, let's examine a couple of options of how to express the relationships.
The closest analog to this would be references.
Currently there are two ways to define a reference:

1. The traditional way has been to annotate a field `@Reference` and Morphia applies magic behind the scenes using proxies to make lazy references work.
This has worked well enough in the past but the proxy-based implementation gets a bit complicated.
If a developer forgets to include the proxy library, lazy references are not possible and suddenly all references become eager references and queries are silently more expensive than perhaps were intended.
On other hand, these fields can be assigned and accessed like any other field on a class without regard to or even knowledge of its reference status.
2. The newer, currently "experimental", approach is to use the wrapper type `MorphiaReference`.
This approach is a bit more opaque in that developers must create these references using `MorphiaReference#wrap()` to create the reference wrapper.
To access the value one must use `MorphaReference#get()` to retrieve the value.
This exposes the implementation detail of the reference but it makes it obvious that it *is* a reference and so could incur extra cost in retrieving.
In addition, all such references are lazy by default without regard to the presence of any proxying library and so yields no surprise costs.

Similar options will be covered here and then some follow up discussion/questions on short comings.

==== Traditional Style

Mapping a GridFS item would require the following annotation:

[source,java]
----
public @interface GridFS {
    /**
     * @return The name of the bucket to use when storing the item.  By default, the {@code fs} bucket will be used.
     */
    String value() default Mapper.IGNORED_FIELDNAME;
}
----

This would allow for simple mapping scenarios:

[source,java]
----
@Entity
public class ImageUpload {
    @Id
    private ObjectId id;
    private double[] coordinates;
    private String[] tags;
    @GridFS("images")
    private Image image;
}
----

The perks of this approach include its utter simplicity.
There's very little surface area required to learn.
The API feels familiar for those who've used references in the past.
It has a few issues to discuss:

1. It makes proxying mandatory.
There is no way to make the GridFS fetch lazy without proxying.
On the one hand, it's a reasonably solved problem.
On the other, the implementation is a bit complex with unexpected sharp edges here and there.
2. There's no way to stream the data like this.
Because it's mapped as an image, the data would all need to be read in to memory so the image could be created.
3. A Codec would need to be created to handle whatever data is stored in GridFS. Of course, this isn't unique to this solution so shouldn't be weighted too heavily.
Alternately, this GridFS data could be mapped to a `byte[]` and then no conversion would be necessary.
4. This setup isn't entirely future proof.
The annotation as defined doesn't currently allow for any knob turning in regards to how an element gets stored.
While attributes could be added to the annotation, it could only ever be a subset of what the datbase supports. e .g., the `metadata` field could never be fully utilized in this scenario since anything defined on the annotation would be applied to every item uniformly.
Any missing attributes could be added later to the annotation but that would not be binary compatible even with default values on the new attributes.
5. This approach currently exposes no lifecycle management options. e.g., how would one delete the `Image` stored here?
Methods could be added to, say, `Datastore` but then the API starts to spread out a bit.

==== Wrapper Style

A new wrapper type will be introduced with helper methods:

[source,java]
----
public class GridFSItem {
    public static <T> GridFSItem<T> store(T item);
    public static <T> GridFSItem<T> store(T item, GridFSOptions options); // Potentially leaks mapping information

    public static <T> GridFSItem<T> store(InputStream stream);
    public static <T> GridFSItem<T> store(InputStream stream, GridFSOptions options); // Potentially leaks mapping information

    public static <T> GridFSItem<T> store(String bucket, T item);
    public static <T> GridFSItem<T> store(String bucket, T item, GridFSOptions options); // Potentially leaks mapping information

    public T get();
    public InputStream stream();
    public void delete();
}
----

[source,java]
----
@Entity
public class ImageUpload {
    @Id
    private ObjectId id;
    private double[] coordinates;
    private String[] tags;
    //    @GridFS("images")  // Possible helper annotation?
    private GridFSItem<Image> image;
}
----

Like the reference wrapper approach, this is a bit more opaque but allows for expansion via new methods in the future.
Some issues to consider:

1. Typed `GridFSItems` will also require a Codec of some sort.
Alternately, `store()`/`stream()` could be overloaded to take lambdas tospecify how to de/serialize the data.
2. Mapping to a specific bucket either requires a bucket name being passed in to the `store()` method (thus, moving mapping information potentially outside of the mapped class) or a helper annotation on the field to list the bucket name.
3. Item specific `GridFSOptions` would need to be passed to `store()`.
This potentially moves mapping information awayfrom the entity (perhaps to a DAO or repository class) but does at least allow element specific metadata, e.g., to be attached to an item without such data being globally applied via the annotation.

There is an inclination to map `Image` itself with various GridFS related data but such mapping are not possible with externally defined third party types.

==== Conclusion

In general, the wrapper approach seems to be the most robust at the cost of a little ceremony around its usage.
Comments for or against either approach are welcome.
Such comments should be left on the https://github.com/MorphiaOrg/morphia/issues/153[GridFS issue].
One element that has not been discussed here is the on disk representation of a GridFS reference.
This is intentional for now as it's easier to focus on the user facing aspects and then figure out how to appropriately store the necessary bits once those are determined.
The format is likely to look largely the same in either case.