name: cleanup.yml

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'


jobs:
  CleanUp:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: dmvict/clean-workflow-runs@v1.0.0
