name: Pull Requests

on:
  pull_request:

jobs:
  CodeAudits:
    uses: evanchooly/workflows/.github/workflows/code-audits.yml@master
    with:
      java: 17
  Build:
    strategy:
      matrix:
        mapper: [reflection, critter]
    uses: evanchooly/workflows/.github/workflows/pull-request.yml@master
    with:
      java: 17
      mapper: ${{ matrix.mapper }}
