name: Quick Build

on:
  push:
  workflow_dispatch:

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: 17
      maven-flags: "-e -DskipTests"

  Release:
    needs:
      - Build
    uses: evanchooly/workflows/.github/workflows/jreleaser.yml@master
    with:
      java: 17
    secrets:
      GH_PUSH_TOKEN       : ${{ secrets.GH_PUSH_TOKEN }}
      MAVEN_GPG_PASSPHRASE      : ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      GPG_PUBLIC_KEY      : ${{ secrets.GPG_PUBLIC_KEY }}
      GPG_PRIVATE_KEY     : ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_USERNAME   : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_TOKEN   : ${{ secrets.SONATYPE_TOKEN }}

